name: app_travell
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.8
  provider: ^6.1.5

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.3
  go_router: ^15.1.2
  http: ^1.2.0
  google_fonts: ^6.2.1
  lottie: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/city/DUBAI.jpg
    - assets/images/city/paris.jpg
    - assets/images/city/moscow.jpg
    - assets/images/beach/beachsharam.jpg
    - assets/images/beach/maldiv.jpg
    - assets/images/mostvisited/roma.jpg
    - assets/images/mostvisited/ryiadh.jpg
    - assets/images/mostvisited/istanbul.jpg
    - assets/images/logo/photologin.jpg
    - assets/animations/palne.json
